---
title: "COVID in Schools"
author: "Wyatt Hurt"
date: "2/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(janitor)
library(tidycensus)
library(leaflet)
library(tidyverse)
library(ggmap)
library(maps)
library(mapproj)
```

```{r load_data}

# SOURCE: https://osf.io/xhrc4/
  
  
aussie_toilets <- read_csv("jill_exercise/aussie_public_toilets.csv")

australia <- map_data("world") %>% filter(region=="Australia")

ggplot() +
  geom_polygon(data = australia, aes(x=long, y = lat, group = group), fill="black") +
  geom_point(data = aussie_toilets, aes(x = Longitude, y = Latitude, color = factor(PaymentRequired, levels = c(TRUE,FALSE))), size = 1) +
  theme_void()+
  coord_map() +
  ylim(-45,-5) + 
  labs(title = "Where is payment required to\nuse public restrooms in Australia?", color = "Payment required?", subtitle= "It appears that Australians like free bathrooms.") + 
    scale_color_discrete(labels = c("Yes", "No"))
```

```{r}
map <- get_googlemap("Australia", zoom = 8, maptype = "terrain")

ggmap(map) + 
  theme_void() + 
  ggtitle("Grand Junction, CO") + 
  theme(
    panel.border = element_rect(colour = "grey", fill=NA, size=2)
  )


```

